name: Publish Package to npmjs

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: PublishToNPM
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          always-auth: true
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run publish
        env: # More info about the environment variables in the README
          NODE_AUTH_TOKEN: ${{ secrets.NPM_JITBITJS_TOKEN }}
